# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       xorg-x11-proto-dmxproto
Summary:    X.Org X11 Protocol dmxproto
Version:    2.3.1
Release:    0
Group:      Development/System
License:    MIT
URL:        http://www.x.org
Source0:    http://xorg.freedesktop.org/releases/individual/proto/dmxproto-%{version}.tar.bz2
Source100:  xorg-x11-proto-dmxproto.yaml
Provides:   dmxproto


%description
This extension defines a protocol for clients to access a front-end proxy X server that controls multiple back-end X servers making up a large display



%prep
%setup -q -n dmxproto-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --libdir=%{_datadir}

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
# >> files
%{_includedir}/X11/extensions/dmx.h
%{_includedir}/X11/extensions/dmxproto.h
%{_datadir}/pkgconfig/dmxproto.pc
# << files


